
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2024-01-02T18:20:42.464Z
 * Generated source version: 3.6.2
 *
 */

@javax.jws.WebService(
                      serviceName = "CpaRentalsSoapUtilityService",
                      portName = "CpaRentalsSoapUtilityPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/CpaRentalsSoapUtility999/services/CpaRentalsSoapUtilityPort?wsdl",
                      endpointInterface = "default_package.CpaRentalsSoapUtility")

public class CpaRentalsSoapUtilityPortImpl implements CpaRentalsSoapUtility {

    private static final Logger LOG = Logger.getLogger(CpaRentalsSoapUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#login(java.lang.String arg0, java.lang.String arg1)*
     */
    public int login(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation login");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 598455756;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#testRMI(int arg0)*
     */
    public java.lang.String testRMI(int arg0) throws NotBoundException_Exception,  MalformedURLException_Exception   {
        LOG.info("Executing operation testRMI");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return189845991";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NotBoundException_Exception("NotBoundException...");
        //throw new MalformedURLException_Exception("MalformedURLException...");
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#getReservationsByUserId(int arg0)*
     */
    public java.lang.String getReservationsByUserId(int arg0) {
        LOG.info("Executing operation getReservationsByUserId");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return432418208";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#cancelReserva(int arg0, int arg1)*
     */
    public java.lang.String cancelReserva(int arg0, int arg1) {
        LOG.info("Executing operation cancelReserva");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return866013323";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#getAvailableSombrinhas(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public java.lang.String getAvailableSombrinhas(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3) throws NotBoundException_Exception,  MalformedURLException_Exception   {
        LOG.info("Executing operation getAvailableSombrinhas");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return2145251365";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NotBoundException_Exception("NotBoundException...");
        //throw new MalformedURLException_Exception("MalformedURLException...");
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#registerUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public int registerUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation registerUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -290346990;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#getDailyOcupationTable(int arg0, java.lang.String arg1, java.lang.String arg2)*
     */
    public java.lang.String getDailyOcupationTable(int arg0, java.lang.String arg1, java.lang.String arg2) {
        LOG.info("Executing operation getDailyOcupationTable");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return-358106253";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#cancelReservation(int arg0)*
     */
    public java.lang.String cancelReservation(int arg0) {
        LOG.info("Executing operation cancelReservation");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-210468473";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#initConnection(java.lang.String arg0)*
     */
    public java.lang.String initConnection(java.lang.String arg0) throws NotBoundException_Exception,  MalformedURLException_Exception   {
        LOG.info("Executing operation initConnection");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1728683177";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NotBoundException_Exception("NotBoundException...");
        //throw new MalformedURLException_Exception("MalformedURLException...");
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#getReservasTable(int arg0)*
     */
    public java.lang.String getReservasTable(int arg0) {
        LOG.info("Executing operation getReservasTable");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1248391573";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#addReservation(int arg0, int arg1)*
     */
    public java.lang.String addReservation(int arg0, int arg1) {
        LOG.info("Executing operation addReservation");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return1585770373";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#getReservationById(int arg0)*
     */
    public java.lang.String getReservationById(int arg0) {
        LOG.info("Executing operation getReservationById");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1280210665";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.CpaRentalsSoapUtility#makeReservation(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3, int arg4)*
     */
    public java.lang.String makeReservation(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3, int arg4) {
        LOG.info("Executing operation makeReservation");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.String _return = "_return-1269305092";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
