
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2024-01-02T18:20:42.316Z
 * Generated source version: 3.6.2
 *
 */
public final class CpaRentalsSoapUtility_CpaRentalsSoapUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://default_package/", "CpaRentalsSoapUtilityService");

    private CpaRentalsSoapUtility_CpaRentalsSoapUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CpaRentalsSoapUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CpaRentalsSoapUtilityService ss = new CpaRentalsSoapUtilityService(wsdlURL, SERVICE_NAME);
        CpaRentalsSoapUtility port = ss.getCpaRentalsSoapUtilityPort();

        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "_login_arg0-1720571147";
        java.lang.String _login_arg1 = "_login_arg1903725190";
        int _login__return = port.login(_login_arg0, _login_arg1);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking testRMI...");
        int _testRMI_arg0 = 1361007492;
        try {
            java.lang.String _testRMI__return = port.testRMI(_testRMI_arg0);
            System.out.println("testRMI.result=" + _testRMI__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getReservationsByUserId...");
        int _getReservationsByUserId_arg0 = 1413147907;
        java.lang.String _getReservationsByUserId__return = port.getReservationsByUserId(_getReservationsByUserId_arg0);
        System.out.println("getReservationsByUserId.result=" + _getReservationsByUserId__return);


        }
        {
        System.out.println("Invoking cancelReserva...");
        int _cancelReserva_arg0 = -791083823;
        int _cancelReserva_arg1 = 413463879;
        java.lang.String _cancelReserva__return = port.cancelReserva(_cancelReserva_arg0, _cancelReserva_arg1);
        System.out.println("cancelReserva.result=" + _cancelReserva__return);


        }
        {
        System.out.println("Invoking getAvailableSombrinhas...");
        int _getAvailableSombrinhas_arg0 = -802765125;
        int _getAvailableSombrinhas_arg1 = -873240339;
        java.lang.String _getAvailableSombrinhas_arg2 = "_getAvailableSombrinhas_arg2-1468810943";
        java.lang.String _getAvailableSombrinhas_arg3 = "_getAvailableSombrinhas_arg3171448521";
        try {
            java.lang.String _getAvailableSombrinhas__return = port.getAvailableSombrinhas(_getAvailableSombrinhas_arg0, _getAvailableSombrinhas_arg1, _getAvailableSombrinhas_arg2, _getAvailableSombrinhas_arg3);
            System.out.println("getAvailableSombrinhas.result=" + _getAvailableSombrinhas__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking registerUser...");
        java.lang.String _registerUser_arg0 = "_registerUser_arg01151673582";
        java.lang.String _registerUser_arg1 = "_registerUser_arg1-718312229";
        int _registerUser__return = port.registerUser(_registerUser_arg0, _registerUser_arg1);
        System.out.println("registerUser.result=" + _registerUser__return);


        }
        {
        System.out.println("Invoking getDailyOcupationTable...");
        int _getDailyOcupationTable_arg0 = 231463836;
        java.lang.String _getDailyOcupationTable_arg1 = "_getDailyOcupationTable_arg11040908248";
        java.lang.String _getDailyOcupationTable_arg2 = "_getDailyOcupationTable_arg2987279716";
        java.lang.String _getDailyOcupationTable__return = port.getDailyOcupationTable(_getDailyOcupationTable_arg0, _getDailyOcupationTable_arg1, _getDailyOcupationTable_arg2);
        System.out.println("getDailyOcupationTable.result=" + _getDailyOcupationTable__return);


        }
        {
        System.out.println("Invoking cancelReservation...");
        int _cancelReservation_arg0 = 1465565297;
        java.lang.String _cancelReservation__return = port.cancelReservation(_cancelReservation_arg0);
        System.out.println("cancelReservation.result=" + _cancelReservation__return);


        }
        {
        System.out.println("Invoking initConnection...");
        java.lang.String _initConnection_arg0 = "_initConnection_arg0-311996746";
        try {
            java.lang.String _initConnection__return = port.initConnection(_initConnection_arg0);
            System.out.println("initConnection.result=" + _initConnection__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getReservasTable...");
        int _getReservasTable_arg0 = -921405239;
        java.lang.String _getReservasTable__return = port.getReservasTable(_getReservasTable_arg0);
        System.out.println("getReservasTable.result=" + _getReservasTable__return);


        }
        {
        System.out.println("Invoking addReservation...");
        int _addReservation_arg0 = 1628395495;
        int _addReservation_arg1 = 913364662;
        java.lang.String _addReservation__return = port.addReservation(_addReservation_arg0, _addReservation_arg1);
        System.out.println("addReservation.result=" + _addReservation__return);


        }
        {
        System.out.println("Invoking getReservationById...");
        int _getReservationById_arg0 = 1124414397;
        java.lang.String _getReservationById__return = port.getReservationById(_getReservationById_arg0);
        System.out.println("getReservationById.result=" + _getReservationById__return);


        }
        {
        System.out.println("Invoking makeReservation...");
        int _makeReservation_arg0 = 1304589245;
        int _makeReservation_arg1 = 830007739;
        java.lang.String _makeReservation_arg2 = "_makeReservation_arg21295251957";
        java.lang.String _makeReservation_arg3 = "_makeReservation_arg31656386117";
        int _makeReservation_arg4 = -1982731481;
        java.lang.String _makeReservation__return = port.makeReservation(_makeReservation_arg0, _makeReservation_arg1, _makeReservation_arg2, _makeReservation_arg3, _makeReservation_arg4);
        System.out.println("makeReservation.result=" + _makeReservation__return);


        }

        System.exit(0);
    }

}
