package default_package;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2024-01-02T18:20:42.506Z
 * Generated source version: 3.6.2
 *
 */
@WebServiceClient(name = "CpaRentalsSoapUtilityService",
                  wsdlLocation = "http://localhost:8080/CpaRentalsSoapUtility999/services/CpaRentalsSoapUtilityPort?wsdl",
                  targetNamespace = "http://default_package/")
public class CpaRentalsSoapUtilityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://default_package/", "CpaRentalsSoapUtilityService");
    public final static QName CpaRentalsSoapUtilityPort = new QName("http://default_package/", "CpaRentalsSoapUtilityPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CpaRentalsSoapUtility999/services/CpaRentalsSoapUtilityPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CpaRentalsSoapUtilityService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CpaRentalsSoapUtility999/services/CpaRentalsSoapUtilityPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CpaRentalsSoapUtilityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CpaRentalsSoapUtilityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CpaRentalsSoapUtilityService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CpaRentalsSoapUtilityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CpaRentalsSoapUtilityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CpaRentalsSoapUtilityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CpaRentalsSoapUtility
     */
    @WebEndpoint(name = "CpaRentalsSoapUtilityPort")
    public CpaRentalsSoapUtility getCpaRentalsSoapUtilityPort() {
        return super.getPort(CpaRentalsSoapUtilityPort, CpaRentalsSoapUtility.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CpaRentalsSoapUtility
     */
    @WebEndpoint(name = "CpaRentalsSoapUtilityPort")
    public CpaRentalsSoapUtility getCpaRentalsSoapUtilityPort(WebServiceFeature... features) {
        return super.getPort(CpaRentalsSoapUtilityPort, CpaRentalsSoapUtility.class, features);
    }

}
